### ISSUE TITLE
Plugin not compatible with Unraid 6.12

### ISSUE THREAD

**Issue by Joly0** [Squidly271/docker.folder#6]
It looks like this plugin is not compatible with Unraid 6.12. It will show as installed, but no settings, no buttons or anything to configure the plugin and previously working docker folders are gone

**Comment by Squidly271** [comment]
Understood.  It's been forked by thecode and is no longer under my control.

**Comment by Joly0** [comment]
> Understood. It's been forked by thecode and is no longer under my control.

Ok, i understand that, but i looked up his fork and searched his repos and there is nothing uptodate. I cant even open an issue on his fork to raise this problem to his attention
