### ISSUE TITLE
PR reverted?

### ISSUE THREAD

**Issue by bdr99** [Squidly271/docker.folder#7]
It looks like the change I made in my PR https://github.com/Squidly271/docker.folder/pull/5 was reverted in https://github.com/Squidly271/docker.folder/commit/48b25858bb5c38b848f9979d09947997a2587d2e. Was this intentional? If there was an issue with the change I would be happy to fix it.

**Comment by Squidly271** [comment]
I was in a hurry to get a compatibility fix out and diidn't worry about anything that wasn't in the release version

**Comment by bdr99** [comment]
I have opened https://github.com/Squidly271/docker.folder/pull/8 to re-add this change.
